In [1]:
number = int(input("enter a number: "))
sqrt = number ** 0.5
print("square root:", sqrt)

enter a number: 25
square root: 5.0


In [4]:
import cmath  
a = float(input('Enter a: '))  
b = float(input('Enter b: '))  
c = float(input('Enter c: '))  
  
# calculate the discriminant  
d = (b**2) - (4*a*c)  
  
# find two solutions  
sol1 = (-b-cmath.sqrt(d))/(2*a)  
sol2 = (-b+cmath.sqrt(d))/(2*a)  
print('The solution are {0} and {1}'.format(sol1,sol2))   

Enter a: 1
Enter b: 7
Enter c: 12
The solution are (-4+0j) and (-3+0j)


In [6]:
x = input('Enter value of x: ')
y = input('Enter value of y: ')

# create a temporary variable and swap the values
temp = x
x = y
y = temp

print('The value of x after swapping: {}'.format(x))
print('The value of y after swapping: {}'.format(y))

Enter value of x: 4
Enter value of y: 5
The value of x after swapping: 5
The value of y after swapping: 4


In [ ]:
# Python program to check if the number is an Armstrong number or not

# take input from the user
num = int(input("Enter a number: "))

# initialize sum
sum = 0

# find the sum of the cube of each digit
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10

# display the result
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

In [8]:
import math
#prints 12
print("the gcd of 60 and 48 is:",end="")
print(math.gcd(60,48))

the gcd of 60 and 48 is:12


In [8]:
#HCF
#define a fnction
def compute_hcf(x,y):
#choose the smaller number
 if x > y :
    smaller=y
 else:
    smaller=x
 for i in range(1,smaller+1):
    if((x%i==0)and (y%i==0)):
        hcf=i
 return hcf
num1=int(input("enter the number:"))
num2=int(input("enter the number:"))
print("the HCF is",compute_hcf(num1,num2))

enter the number:60
enter the number:48
the HCF is 12


In [6]:
import math
print("the lcm is:",end="")
print(math.lcm(60,48))

the lcm is:240


In [12]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


In [10]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [11]:
dict1 = {1: 1, 2: 9, 3: 4}
sorted_values = sorted(dict1.values()) # Sort the values
sorted_dict = {}

for i in sorted_values:
    for k in dict1.keys():
        if dict1[k] == i:
            sorted_dict[k] = dict1[k]

print(sorted_dict)

{1: 1, 3: 4, 2: 9}


In [13]:
from datetime import datetime
date_object = datetime.strptime('Jul 1 2014 2:43PM', '%b %d %Y %I:%M%p')
print(date_object)

2014-07-01 14:43:00


In [14]:
num = 1234
reversed_num = 0

while num != 0:
    digit = num % 10
    reversed_num = reversed_num * 10 + digit
    num //= 10

print("Reversed Number: " + str(reversed_num))

Reversed Number: 4321


In [15]:
base = 3
exponent = 4

result = 1

while exponent != 0:
    result *= base
    exponent-=1

print("Answer = " + str(result))

Answer = 81


In [17]:
import time

def countdown(time_sec):
    while time_sec:
        mins, secs = divmod(time_sec, 60)
        timeformat = '{:02d}:{:02d}'.format(mins, secs)
        print(timeformat, end='\r')
        time.sleep(1)
        time_sec -= 1

    print("stop")

countdown(5)

stop1


In [1]:
byteData = b"Lets eat a \xf0\x9f\x8d\x95!"  
# Let's check the type  
print(type(byteData))  
str1 = byteData.decode('UTF-8')  
print(type(str1))  
print(str1)  

<class 'bytes'>
<class 'str'>
Lets eat a 🍕!


In [2]:
#program to convert byte to string
# Program for converting bytes
# to string using decode()

data = b'ComputerScience'

# display input
print('\nInput:')
print(data)
print(type(data))

# converting
output = data.decode()

# display output
print('\nOutput:')
print(output)
print(type(output))



Input:
b'ComputerScience'
<class 'bytes'>

Output:
ComputerScience
<class 'str'>


In [6]:
# Python program to merge two files 
data = data2 = "" 
  
# Reading data from first file 
with open('f1.txt') as fp: 
    data= fp.read() 
with open('f2.txt') as fp: 
    data2 = fp.read() 
# Merging two files into one another file 
data += "\n"
data += data2 
with open ('f3.txt', 'w') as fp: 
    fp.write(data)

In [17]:
graph={
    '1':['2','10'],
    '2':['3','8'],
    '3':['4'],
    '4':['5','6','7'],
    '5':[],
    '6':[],
    '7':[],
    '8':['9'],
    '9':[],
    '10':[]
}
visited=[]
queue=[]
def bfs(visited,graph,node):
    visited.append(node)
    queue.append(node)
    while queue:
        m=queue.pop(0)
        print(m,end=" ")
        for neighbour in graph[m]:
            if neighbour not in visited:
                visited.append(neighbour)
                queue.append(neighbour)
print("Following the BFS")
bfs(visited,graph,'1')

Following the BFS
1 2 10 3 8 4 9 5 6 7 

In [2]:
# Using a Python dictionary to act as an adjacency list
graph = {
    '5' : ['3','7'],
    '3' : ['2', '4'],
    '7' : ['6'],
    '6': [],
    '2' : ['1'],
    '1':[],
    '4' : ['8'],
    '8' : []
}
visited = set() # Set to keep track of visited nodes of graph.
def dfs(visited, graph, node): #function for dfs
    if node not in visited:
        print (node)
        visited.add(node)
        for neighbour in graph[node]:
            dfs(visited, graph, neighbour)

# Driver Code
print("Following is the Depth-First Search")
dfs(visited, graph, '5')

Following is the Depth-First Search
5
3
2
1
4
8
7
6


In [3]:
# Iterative Binary Search Function method Python Implementation  
# It returns index of n in given list1 if present,   
# else returns -1   
def binary_search(list1, n):  
    low = 0  
    high = len(list1) - 1  
    mid = 0  
  
    while low <= high:  
        # for get integer result   
        mid = (high + low) // 2  
  
        # Check if n is present at mid   
        if list1[mid] < n:  
            low = mid + 1  
  
        # If n is greater, compare to the right of mid   
        elif list1[mid] > n:  
            high = mid - 1  
  
        # If n is smaller, compared to the left of mid  
        else:  
            return mid  
  
            # element was not present in the list, return -1  
    return -1  
  
  
# Initial list1  
list1 = [12, 24, 32, 39, 45, 50, 54]  
n = 50
  
# Function call   
result = binary_search(list1, n)  
  
if result != -1:  
    print("Element is present at index", str(result))  
else:  
    print("Element is not present in list1")  


Element is present at index 5


In [3]:
from queue import PriorityQueue
import matplotlib.pyplot as plt
import networkx as nx
def best_first_search(source,target,n):
    visited=[0]*n
    visited[source]=True
    pq=PriorityQueue()
    pq.put((0,source))
    while pq.empty()==False:
        u=pq.get()[1]
        print(u,end="")
        if u==target:
            break
        for v,c in graph[u]:
            if visited[v]==False:
                visited[v]=True
                pq.put((c,v))
    print()
def addedge(x,y,cost):
    graph[x].append((y,cost))
    graph[y].append((x,cost))
    
v=int(input("enter the number of nodes:"))
graph=[[] for i in range(v)]
e=int(input("Enter the number of edges:"))
print("Enter the edges along with their weights")
for i in range(e):
    x,y,z=list(map(int,input().split()))
    addedge(x,y,z)
source=int(input("Enter the source node:"))
target=int(input("enter the target/destination node:"))
print("\nPath:",end="")
best_first_search(source,target,v)

enter the number of nodes:4
Enter the number of edges:5
Enter the edges along with their weights
0 1 1
0 2 1
0 3 2
2 3 2
1 3 3
Enter the source node:2
enter the target/destination node:1

Path:201


In [9]:
from collections import defaultdict
jug1,jug2,aim=4,3,2
visited=defaultdict(lambda:False)
def waterJugSolver(amt1,amt2):
    if(amt1==aim and amt2==0)or(amt2==aim and amt1==0):
        print(amt1,amt2)
        return True
    if visited[(amt1,amt2)]==False:
        print(amt1,amt2)
        visited[(amt1,amt2)]=True
        return(waterJugSolver(0,amt2)or
            waterJugSolver(amt1,0)or
            waterJugSolver(jug1,amt2)or
            waterJugSolver(amt1,jug2)or
            waterJugSolver(amt1+min(amt2,(jug1-amt1)),
            amt2-min(amt2,(jug1-amt1))) or
            waterJugSolver(amt1-min(amt1,(jug2-amt2)),
            amt2+min(amt1,(jug2-amt2))))
    else:
        return False
print("steps:")
waterJugSolver(0,0)
    

steps:
0 0
4 0
4 3
0 3
3 0
3 3
4 2
0 2


True

In [13]:
def TowerOfHanoi(n,source,destination,auxiliary):
    if n==1:
        print("Move desk 1 from source",source,"to destination",destination)
        return
    TowerOfHanoi(n-1,source,auxiliary,destination)
    print("Move disk",n,"form source",source,"to destination",destination)
    TowerOfHanoi(n-1,auxiliary,destination,source)
n=3
TowerOfHanoi(n,'A','B','C')

Move desk 1 from source A to destination B
Move disk 2 form source A to destination C
Move desk 1 from source B to destination C
Move disk 3 form source A to destination B
Move desk 1 from source C to destination A
Move disk 2 form source C to destination B
Move desk 1 from source A to destination B


In [2]:
import numpy as np
import random
from time import sleep
def create_board():
    return(np.array([[0,0,0],
                     [0,0,0],
                     [0,0,0]]))
def possibilities(board):
    l=[]
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j]==0:
                l.append((i,j))          
    return(l)

def random_place(board,player):
    selection=possibilities(board)
    current_loc=random.choice(selection)
    board[current_loc]=player
    return(board)
def row_win(board,player):
    for x in range(len(board)):
        win=True
        for y in range(len(board)):
            if board[x,y]!=player:
                win=False
                continue
        if win==True:
            return(win)
    return(win)

def col_win(board,player):
    for x in range(len(board)):
        win=True
        for y in range(len(board)):
            if board[y][x]!=player:
                win=False
                continue
        if win==True:
            return(win)
    return(win)

def diag_win(board,player):
    win=True
    y=0
    for x in range(len(board)):
        if board[x,x]!=player:
            win=False
    if win:
        return win
    win=True
    if win:
        for x in range(len(board)):
            y=len(board)-1-x
            if board[x,y]!=player:
                win=False
        return win
    
def evaluate(board):
    winner=0
    for player in[1,2]:
        if(row_win(board,player)or
          col_win(board,player)or
          diag_win(board,player)):
            winner=player
    if np.all(board!=0)and winner==0:
        winner=-1
    return winner

def play_game():
    board,winner,counter=create_board(),0,1
    print(board)
    sleep(2)
    while winner==0:
        for player in[1,2]:
            board=random_place(board,player)
            print("Board after board" + str(counter) + "move")
            print(board)
            sleep(2)
            counter+=1
            winner=evaluate(board)
            if winner!=0:
                break
    return(winner)
print("Winner is:" + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after board1move
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Board after board2move
[[0 0 0]
 [2 1 0]
 [0 0 0]]
Board after board3move
[[0 0 0]
 [2 1 1]
 [0 0 0]]
Board after board4move
[[0 0 2]
 [2 1 1]
 [0 0 0]]
Board after board5move
[[0 1 2]
 [2 1 1]
 [0 0 0]]
Board after board6move
[[0 1 2]
 [2 1 1]
 [2 0 0]]
Board after board7move
[[1 1 2]
 [2 1 1]
 [2 0 0]]
Board after board8move
[[1 1 2]
 [2 1 1]
 [2 0 2]]
Board after board9move
[[1 1 2]
 [2 1 1]
 [2 1 2]]
Winner is:1


In [10]:
import copy
from heapq import heappush, heappop
n = 3
row = [ 1, 0, -1, 0 ]
col = [ 0, -1, 0, 1 ]

class priorityQueue:
    def __init__(self):
        self.heap = []
    def push(self, k):
        heappush(self.heap, k)
    def pop(self):
        return heappop(self.heap)
    def empty(self):
        if not self.heap:
            return True
        else:
            return False

class node:
    def __init__(self, parent, mat, empty_tile_pos,cost, level):
        self.parent = parent
        self.mat = mat
        self.empty_tile_pos = empty_tile_pos
        self.cost = cost
        self.level = level
    def __lt__(self, nxt):
        return self.cost < nxt.cost
    
    def calculateCost(mat, final) -> int:
        count = 0
        for i in range(n):
            for j in range(n):
                if ((mat[i][j]) and (mat[i][j] != final[i][j])):
                    count += 1
                    return count

    def newNode(mat, empty_tile_pos, new_empty_tile_pos,level, parent, final) -> node:
        new_mat = copy.deepcopy(mat)
        x1 = empty_tile_pos[0]
        y1 = empty_tile_pos[1]
        x2 = new_empty_tile_pos[0]
        y2 = new_empty_tile_pos[1]
        new_mat[x1][y1], new_mat[x2][y2] = new_mat[x2][y2], new_mat[x1][y1]
        cost = calculateCost(new_mat, final)
        new_node = node(parent, new_mat, new_empty_tile_pos,cost, level)
        return new_node

    def printMatrix(mat):
        for i in range(n):
            for j in range(n):
                print("%d " % (mat[i][j]), end = " ")
                print()
    
    def isSafe(x, y):
        return x >= 0 and x < n and y >= 0 and y < n

    def printPath(root):
        if root == None:
            return
        printPath(root.parent)
        printMatrix(root.mat)


    def solve(initial, empty_tile_pos, final):
        pq = priorityQueue()
    
        cost = calculateCost(initial, final)
        root = node(None, initial,empty_tile_pos, cost, 0)
        pq.push(root)
        while not pq.empty():
            minimum = pq.pop()
            if minimum.cost == 0:
                printPath(minimum)
                return
        for i in range(n):
            new_tile_pos = [minimum.empty_tile_pos[0] + row[i],
                            minimum.empty_tile_pos[1] + col[i], ]
            if isSafe(new_tile_pos[0], new_tile_pos[1]):
                child=newNode(minimum.mat,minimum.empty_tile_pos,new_tile_pos,minimum.level +minimum, final,)
                pq.push(child)
initial = [ [ 1, 2, 3 ],[ 5, 6, 0 ],[ 7, 8, 4 ] ]
final = [ [ 1, 2, 3 ],[ 5, 8, 6 ],[ 0, 7, 4 ] ]
empty_tile_pos = [ 1, 2 ]
solve(initial, empty_tile_pos, final)

TypeError: unsupported operand type(s) for +: 'int' and 'node'

In [12]:
from sys import maxsize
from itertools import permutations
V = 4

def travellingSalesmanProblem(graph, s):
    vertex = []
    for i in range(V):
        if i != s:
            vertex.append(i)
        min_path = maxsize
        next_permutation=permutations(vertex)
        for i in next_permutation:
            current_pathweight = 0
            k = s
            for j in i:
                current_pathweight += graph[k][j]
                k = j
            current_pathweight += graph[k][s]
            min_path = min(min_path, current_pathweight)
    return min_path

# Driver Code
if __name__ == "__main__":
    graph = [[0, 10, 15, 20], [10, 0, 35, 25],
             [15, 35, 0, 30], [20, 25, 30, 0]]
    s = 0
    print(travellingSalesmanProblem(graph, s))

80
